name: Connector 
description: New connector submission
labels: [connector-submission]
title: "[Connector submission]: <placeholder-for-connector-name>"
body:
- type: input
    id: name
    attributes:
      label: 'Connector name'
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: 'Connector version'
    validations:
      required: false