name: Collect connectors metadata

defaults:
  run:
    shell: bash

on:
  pull_request:
    types:
      - closed
    branches:
      - main
      
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Collect connector metadata
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v22.2
        with:
          since_last_remote_commit: true
          files: |           
            connectors/**       
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done               
      - name: Collect Metadata
        run: |
          ids=(${{ steps.changed-files.outputs.all_changed_files }});
          if [ ${#ids[@]} -eq 0 ]; then
            echo "No updated connector"
          else            
            cd ${{ github.workspace }}/scripts/
            id="${ids[@]}";
            go run . "collect-metadata" ${{ github.workspace }} connectors-metadata.json archive ${id// /" "}
            cd ${{ github.workspace }}
          fi    
