name: Connector Validation

defaults:
  run:
    shell: bash

on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    name: Validate connector strucure
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v22.2
        with:
          path: './connectors/'
      - name: List changed files
        run: |
          echo "${#steps.changed-files.outputs.all_changed_files[@]}"
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      - name: Connectors validation
        needs: [changed-files]
        run: |
          cd ${{ github.workspace }}/scripts/
          ids=${{ steps.changed-files.outputs.all_changed_files }};id="${ids[@]}";
          go run . ${{ github.workspace }} connector.schema.json ${id// /" "}
          cd ${{ github.workspace }}      
