name: Connector Validation

defaults:
  run:
    shell: bash

on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    name: Validate connector strucure
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v22.2
        with:
          path: '${GITHUB_WORKSPACE}/connectors/'

      - name: Connectors validation
        run: |
          cd ${GITHUB_WORKSPACE}/scripts/
          ids=${{ steps.changed-files.outputs.all_changed_files }};id="${ids[@]}";
          go run . ${GITHUB_WORKSPACE} connector.schema.json ${id// /" "}
          cd ${GITHUB_WORKSPACE}      
